# HOME ASSISTANT DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deployment
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:latest
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: "Europe/Rome"
      volumes:
      - name: config
        hostPath:
          path: /home/docker/data/home-assistant
          type: Directory
---
# HOME ASSISTANT SERVICE
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
  - name: web
    protocol: TCP
    port: 8123
    targetPort: 8123
    nodePort: 30007

