# PI-HOLE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole-deployment
  labels:
    app: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
      - name: pi-hole
        image: pihole/pihole:latest
        volumeMounts:
        - mountPath: /etc/pihole
          name: pi-hole
        - mountPath: /etc/dnsmasq.d
          name: dnsmasq
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
        env:
        - name: TZ
          value: "Europe/Rome"
      volumes:
      - name: pi-hole
        hostPath:
          path: /home/docker/data/pi-hole/config
          type: Directory
      - name: dnsmasq
        hostPath:
          path: /home/docker/data/pi-hole/dnsmasq
          type: Directory
---
# PI-HOLE SERVICE
apiVersion: v1
kind: Service
metadata:
  name: pi-hole-service
spec:
  type: NodePort
  selector:
    app: pi-hole
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30009
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
    nodePort: 30009
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010